# Default configuration file for RSCchecker

# Debug mode is disabled by default.
enable-debug: false
# ignore list
ignores:
  # true or false
  ignoreGroups: false
  ignoreRecipeTypes: false
  ignoreMobDrops: false
  ignoreGeoResources: false
  ignoreItems: false
  ignoreArmors: false
  ignoreCapacitors: false
  ignoreFoods: false
  ignoreMenus: false
  ignoreMachines: false
  ignoreGenerators: false
  ignoreSolarGenerators: false
  ignoreMaterialGenerators: false
  ignoreRecipeMachines: false
  ignoreSimpleMachines: false
  ignoreMultiblockMachines: false
  ignoreSupers: false
  ignoreTemplateMachines: false
  ignoreResearches: false

# addons to scan
scan-files:
  # Relative path only
  addons:
  - "example"

# The maximum number of bugs and warnings to print in the console.
MaxPrintBug: 1000
MaxPrintWarn: 100
# Path of Items.yml and "../../Slimefun/Items.yml" by default
# ex: SlimefunItemsPath: 'D:/yourServerPath/plugins/Slimefun/Items.yml'
SlimefunItemsPath: "default"

# Don't change this
config-version: 16
