# 请勿删除这些配置，否则会影响脚本运行！
# 请勿删除这些配置，否则会影响脚本运行！
# 请勿删除这些配置，否则会影响脚本运行！
# 跳过哪些检查
ignores:
  # 填 true 或 false
  ignoreGroups: false
  ignoreRecipeTypes: false
  ignoreGeoResources: false
  ignoreMobDrops: false
  ignoreItems: false
  ignoreArmors: false
  ignoreCapacitors: false
  ignoreFoods: false
  ignoreMenus: false
  ignoreMachines: false
  ignoreGenerators: false
  ignoreSolarGenerators: false
  ignoreMaterialGenerators: false
  ignoreRecipeMachines: false
  ignoreSimpleMachines: false
  ignoreMultiblockMachines: false
  ignoreResearches: false
  ignoreSupers: false

# 扫描哪些文件
scan-files:
  # 你应该在这里填路径
  # ex: Groups: ['groups.yml'] 暂不支持绝对路径
  #     addons: ['example', 'slimefunExpansion'] 暂不支持绝对路径 
  # 诸如此类 ↑
  addons: ['example']
  Groups: ['groups.yml']
  RecipeTypes: ['recipe_types.yml']
  GeoResources: ['geo_resources.yml']
  MobDrops: ['mob_drops.yml']
  Items: ['items.yml']
  Armors: ['armors.yml']
  Capacitors: ['capacitors.yml']
  Foods: ['foods.yml']
  Menus: ['menus.yml']
  Machines: ['machines.yml']
  Generators: ['generators.yml']
  SolarGenerators: ['solar_generators.yml']
  MaterialGenerators: ['mat_generators.yml']
  RecipeMachines: ['recipe_machines.yml']
  SimpleMachines: ['simple_machines.yml']
  MultiblockMachines: ['mb_machines.yml']
  Researches: ['researches.yml']
  Supers: ['supers.yml']
# 最多打印多少bug
MaxPrintBug: 1000
# 最多打印多少Warn
MaxPrintWarn: 100
# 你应该在这里填粘液物品路径（default指向 ../../Slimefun/Items.yml）
# ex: SlimefunItemsPath: 'D:/plugins/Slimefun/Items.yml'
SlimefunItemsPath: 'default'
